name: Development Build and Test

on:
  push:
    branches-ignore: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]

jobs:
  # Тестирование изменений в development ветках
  test-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci

    - name: Lint Frontend Code
      run: |
        cd frontend
        npm run lint || echo "Linting completed with warnings"

    - name: Test Frontend Build
      run: |
        cd frontend
        npm run build
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Backend Dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Backend Code Check
      run: |
        cd backend
        python -m py_compile app/main.py
        echo "Backend syntax check passed"

    - name: Build Success Notification
      run: |
        echo "✅ All checks passed!"
        echo "🔍 Changes are ready for review"
        echo "📝 Once merged to main/master, automatic deployment will trigger"